#COMPONENT_PRIV_INCLUDEDIRS=. ${PROJECT_PATH}/src/GameState ${PROJECT_PATH}/src/GameState/Playfields ${PROJECT_PATH}/src/GameState/Powerups
#COMPONENT_EXTRA_INCLUDES=${CREATIVE_ENGINE_PATH}/src ${CREATIVE_ENGINE_PATH}/src/Widgets
#COMPONENT_PRIV_INCLUDEDIRS=. ..
#COMPONENT_PRIV_INCLUDEDIRS=. .. ${PROJECT_PATH}/src/GameState/Powerups ${PROJECT_PATH}/src/GameState/Playfields
#COMPONENT_EXTRA_INCLUDES=${CREATIVE_ENGINE_PATH}/src ${CREATIVE_ENGINE_PATH}/src/Widgets ${PROJECT_PATH}/src/GameState/Powerups ${PROJECT_PATH}/src/GameState/Playfields ${PROJECT_PATH}/src/GameState ${PROJECT_PATH}/src
#COMPONENT_PRIV_INCLUDEDIRS=. ${PROJECT_PATH}/src/GameState ${PROJECT_PATH}/src/GameState/Playfields ${PROJECT_PATH}/src/GameState/Powerups
COMPONENT_EXTRA_INCLUDES=${CREATIVE_ENGINE_PATH}/src ${CREATIVE_ENGINE_PATH}/src/Widgets ${PROJECT_PATH}/src ${PROJECT_PATH}/src/GameState ${PROJECT_PATH}/src/GameState/Playfields ${PROJECT_PATH}/src/GameState/Powerups
