# Resource source file
PATH ./data # path to resource files

BITMAP airwars.bmp
BITMAP bkg1.bmp
BITMAP bkg2a.bmp
BITMAP bkg2.bmp
BITMAP bkg3.bmp
BITMAP bkg5.bmp
BITMAP bkg6.bmp
BITMAP bkg7.bmp
BITMAP carrierboss.bmp
BITMAP caution.bmp
BITMAP charset1.bmp
BITMAP common.bmp
BITMAP controls.bmp
BITMAP copyright.bmp
BITMAP credits.bmp
BITMAP explosions.bmp
BITMAP finaltitle2.bmp
BITMAP finaltitle.bmp
BITMAP flame.bmp
BITMAP gulfboss.bmp
BITMAP gulfwar.bmp
BITMAP highscores.bmp
BITMAP jeep2.bmp
BITMAP marquees.bmp
BITMAP music.bmp
BITMAP options.bmp
BITMAP p1.bmp
BITMAP p2.bmp
BITMAP p3.bmp
BITMAP p4.bmp
BITMAP p5.bmp
BITMAP playernew.bmp
BITMAP playernew_more.bmp
BITMAP rules.bmp
BITMAP s1balloonbusting.bmp
BITMAP s2crop.bmp
BITMAP s3islandhopping.bmp
BITMAP s4crop.bmp
BITMAP s5junglefever.bmp
BITMAP s6crop.bmp
BITMAP s7controlair.bmp
BITMAP s8crop.bmp
BITMAP s9future.bmp
BITMAP space.bmp
BITMAP spaceboss01.bmp
BITMAP spaceboss02.bmp
BITMAP spaceboss03.bmp
BITMAP spaceboss.bmp
BITMAP stuckintodirt.bmp
BITMAP urlbanner.bmp
BITMAP vietboss.bmp
BITMAP vietnam.bmp
BITMAP wwi.bmp
BITMAP wwii.bmp
BITMAP zeppelin.bmp
BITMAP zepplinboss.bmp
